{
  'plugins': ['prettier-plugin-jinja-template'],
  'singleQuote': true,
  'printWidth': 140,
  'trailingComma': all,
  'overrides': [{ 'files': '*.html', 'options': { 'parser': 'jinja-template' } }],
}
