apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: keh-tech-audit-tool
  description: Authenticated web application for surveying the tools, languages, and frameworks used across Digital Services and Technology.
  annotations:
    github.com/project-slug: ONS-Innovation/keh-tech-audit-tool
  tags:
    - python
    - flask
    - aws-ecs
    - aws-fargate
    - aws-cognito
  links:
    - url: mailto:knowledge.exchange.hub@ons.gov.uk
      title: Contact
spec:
  type: website
  lifecycle: production
  owner: keh-dev
  dependsOn:
    - component:default/keh-tech-audit-tool-api
