resources:
- name: resource-repo
  type: git
  icon: github
  source:
    uri: https://github.com/ONS-Innovation/keh-tech-audit-tool.git
    branch: concourse

- name: ui-image
  type: registry-image
  icon: docker
  source:
    repository: ((image-repo-name))
    username: ((registry-username))
    password: ((registry-password))
    tag: ((container_ver))

jobs:
- name:  build-and-push
  public: true
  plan:
  - get: resource-repo
    trigger: true
    timeout: 5m
  - task: test-secret
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: hashicorp/terraform}
      inputs:
      - name: resource-repo
      params:
        test_secret: ((test-secret-tat))
      run:
        path: sh
        args: ["./resource-repo/concourse/scripts/test_script.bash"]


  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: resource-repo
      outputs:
      - name: image
      params:
        CONTEXT: resource-repo
      run: # binary used to build the image
        path: build
    timeout: 10m

  - put: ui-image
    params:
      image: image/image.tar
    timeout: 5m

  - task: terraform
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: hashicorp/terraform}
      inputs:
      - name: resource-repo
      params:
        aws_account_id: ((aws_account_id))
        api_secret_name: ((api_secret_name))
        test_secret: ((test-secret-tat))
        domain: ((domain))
        container_ver: ((container_ver))
        api_bucket_name: ((api_bucket_name))
        ui_secret_name: ((ui_secret_name))
        aws_account_name: ((aws_account_name))
        localhost: ((localhost))
        container_image: ((container_image))
        force_deployment: ((force_deployment))
        github_access_token: ((github_access_token))
      run:
        path: sh
        args: ["./resource-repo/concourse/scripts/terraform_infra.bash"]
    timeout: 30m
          