resources:
- name: resource-repo
  type: git
  icon: github
  source:
    uri: https://github.com/ONS-Innovation/keh-tech-audit-tool
    tag_filter: v*
    branch: main

jobs:
- name:  build-and-push
  public: true
  plan:
  - get: resource-repo
    timeout: 5m
  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: hashicorp/terraform
      inputs:
      - name: resource-repo
      params:
        aws_account_id: ((aws_account_sdp_dev))
        aws_role_arn: arn:aws:iam::((aws_account_sdp_dev)):role/sdp-concourse-dev
      run: # binary used to build the image
        path: sh
        args:
        - -cx
        - |
          cd resource-repo
          tag=$(git tag --points-at HEAD | tail -n 1)
          echo ${tag} > tag.txt
          chmod u+x ./concourse/scripts/assume_role.bash
          chmod u+x ./concourse/scripts/build_image.bash
          source ./concourse/scripts/assume_role.bash
          ./concourse/scripts/build_image.bash
    timeout: 10m
  - task: terraform
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: hashicorp/terraform}
      inputs:
      - name: resource-repo
      params:
        tat_secrets_ui: ((sdp_dev_secrets_tat_ui))
        github_access_token: ((github_access_token))
      run:
        path: sh
        args:
        - -cx
        - |
          cd resource-repo
          tag=$(git tag --points-at HEAD | tail -n 1)
          echo ${tag} > tag.txt
          chmod u+x ./concourse/scripts/terraform_infra.bash
          ./concourse/scripts/terraform_infra.bash
    timeout: 30m
            